### ISSUE TITLE
R reverts to using original BLAS

### ISSUE THREAD

**Issue by waynelapierre** [prdm0/ropenblas#12]
After running the function ropenblas(), I checked the session information and confirmed that R now links to Openblas. However, after I do an update to my computer, R reverted to using the original BLAS again, am I supposed to run the ropenblas() for every new session?

By update, I mean run the code sudo dnf update on my fedora operating system.

**Comment by prdm0** [comment]
You will not necessarily have to run `ropenblas()` on every section of R. Almost always it will not be necessary. However, it may be that the R is updated by the operating system (GNU/Linux). Thus, it may be that in this update the R unlink with the OpenBLAS library. Therefore, from time to time check using the command `extSoftVersion()["BLAS"]` if the link with OpenBLAS is correct, otherwise run the command `ropenblas()` again.
