### ISSUE TITLE
JOSS review

### ISSUE THREAD

**Issue by pratikvn** [prdm0/ropenblas#21]
Hello @prdm0 ,

I am a reviewer for the paper you submitted to JOSS. The package is very useful to a lot of R users and I thank you for creating this package. 

I had some comments on the paper. Please find them in the pdf attached. In summary the paper looks good to me. I just had a few suggestions and one aspect that I think is necessary to address:

1. As you claim that the ropenblas provides an improved performance, you should validate this claim by adding some runtime comparisons with and without openblas.

2. Other suggestions are mainly some refactoring and removal of repeated content especially in the second section.

3. There were also some other suggestions mainly addressing some language issues. Some of these might be stylistic, so feel free to disregard them.

[Download the ropenblas_reviewed.pdf](https://github.com/prdm0/ropenblas/files/5541564/ropenblas_reviewed.pdf)

**Comment by prdm0** [comment]
Hello @pratikvn , thank you very much for sending us your suggestions for improvements. It will certainly help to improve the quality of the paper. When the improvements are implemented, should I generate a new PDF at [#2769](https://github.com/openjournals/joss-reviews/issues/2769)?

Is there a maximum time limit for improvements to be implemented?

Kind regards.

**Comment by pratikvn** [comment]
@prdm0 , yes, once you have incorporated the changes, please generate a new PDF. I am not aware of any maximum time limit, but the editor might be able to answer that better.

**Comment by pratikvn** [comment]
@prdm0 , I had a few more comments to address some of the Functionality and the Documentation requirements:

1. Can you please re-factor the README.md file and only keep minimal installation instructions, dependency information, a small example and the last section on Advantages in README ? And move the rest to a separate INSTALL.md file. I think this makes the README a little easier to read and if you can add a table of contents, this would make the navigation much better. [See related Stackoverflow question and accepted answer](https://stackoverflow.com/questions/2822089/how-to-link-to-part-of-the-same-document-in-markdown)

2. I guess there are no automated tests you can implement for this repository ? Maybe running on some dataset on the github actions CI or your preferred CI setup ? 

3. Could you also add a CONTRIBUTING.md file? This helps other people contribute to this repository. See [github blog](https://github.blog/2012-09-17-contributing-guidelines/).

4. As you claim that the performance is better when using an openblas backend, I think you should verify this. You could even add a plot to the README.

**Comment by prdm0** [comment]
@pratikvn  thanks for the suggestions. I will try to implement most of the suggestions.

I am waiting for the second reviewer to present his suggestions so that I can implement everything at once. This would prevent me from modifying the files and documentation that he may already be correcting.

On performance, I will perform some benchmark to prove it, although it is already known that the performance of OpenBLAS is inferior to that of the BLAS library ([see](http://blog.nguyenvq.com/blog/2014/11/10/optimized-r-and-python-standard-blas-vs-atlas-vs-openblas-vs-mkl/)). However, I agree that it would be interesting to add this to the article. This would make the paper easier to read. I had even made benchmarks and removed it, since the Editor had asked to shrink the paper that previously had 13 pages to 4 pages.

There is also a library website that was built at [RMarkdown](https://rmarkdown.rstudio.com/).  Detail in **<https://prdm0.github.io/ropenblas/>**.

I will try to create a REAMD.md with an index to facilitate navigation between the information, following the sections you suggested.

**Comment by prdm0** [comment]
@pratikvn, I made several modifications to [README.md](https://github.com/prdm0/ropenblas/blob/master/README.md) and others requested. I believe that it is now easier to read [README.md](https://github.com/prdm0/ropenblas/blob/master/README.md). I put the index with the navigation links and created the file [CONTRIBUTING.md](https://github.com/prdm0/ropenblas/blob/master/CONTRIBUTING.md).

**Comment by pratikvn** [comment]
@prdm0 , thanks for adding the changes. As one of the final steps, I would strongly recommend to pass the whole paper through a grammar correctness check. You can use free tools such as Grammarly (https://www.grammarly.com/) to improve your sentence structure and the overall readability of your paper.

**Comment by prdm0** [comment]
Hello @pratikvn, I will do that. Thanks for the sugestion.

**Comment by prdm0** [comment]
Dear @pratikvn , I followed your suggestion and made some corrections to the text using the tool. Until the text behaved very well and few errors were found. Thank you very much for the suggestion

**Comment by pratikvn** [comment]
@prdm0 , some final comments: 
[annotated.pdf](https://github.com/prdm0/ropenblas/files/6114062/annotated.pdf)

**Comment by prdm0** [comment]
@pratikvn, thanks for the suggestions. I will provide these improvements.

**Comment by pratikvn** [comment]
The paper looks good from my side.
